### ISSUE TITLE
Path name clarifications

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#1193]
I keep explaining when a path is wrapped from a CS3 _global path_ to a _storage relative path_ and to an _internal path_ ... and what that might mean. My head hurts, so let me know what you think of this glossary:

_Note: the *we* used below is intended to be understood as a common agreement. This is just my personal opinion, but maybe you agree with me. If you don't: leave feedback so we can improve this and make an official glossary out of it._

# Endpoints

Clients access files using `endpoints`:

- https://cloud.example.org/remote.php/webdav
- https://cloud.example.org/remote.php/dav/files/<userid>

# Path

A `path` is what the user sees, eg `/path/to/file.md`

but it is relative to the endpoint:

- https://cloud.example.org/remote.php/webdav/path/to/file.md
- https://cloud.example.org/remote.php/dav/files/<userid>/path/to/file.md

The ocdav service translates requests from webdav to cs3 and tus.

# CS3 namespace

In the cs3 api a file or folder is represented using a [`Reference`](https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.Reference), which can either be:
- an absolute path, starting with `/`, or
- a [ResourceID](https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.ResourceId) with a storage id and an opaque id that the storage provider can use to look up the file or folder.
- [ ] A resource should allow both at the same time: a ResourceID to reference the root node as well as a path relative (no leading `/` in that case) to that node. The MS graph API does it that way and it allows linking to resources and attaching sharing information to the reference, eg. for symbolic links or temporary download / upload links.

The absolute path used when talking with a CS3 gateway creates a new CS3 namespace which makes storage providers accessible using a global namespace. At `/home` reva and ocis mount a home storage that lists the users private files, as well as a _Shared_ folder, eg `/home/Shares` that contains the accepted shares.

In addition to that there may be a storage provider mounted at `/eos` or `/oc` that are used to access shared files from other users.
- [ ] This should be unified to `/users`, the storage driver name has nothing to do with what the storage is used for.

In the future other storages could be mounted under `/projects` or `/spaces`.

Another CS3 namespace ocis uses is `/meta` to store account metadata.

When the gateway receives a path it is always a _global path_. We recommend `gp` for the variable name and `gpath` for logging.

# Storage relative path

A storage provider receives CS3 api calls which use [`References`](https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.Reference) and must be able to look up path based as well as id based references.

So while all calls will see a reference they need to look up the storage relative path, eg to determine the grants that are affecting the permissions of the current node or to check that the id based reference is not part of an already deleted tree. This is where the code needs to use a variable name the describes what kind of path this is. The path in the reference MUST start with a `/` but it is actually only relative in the cs3 namespace, so let us call it _storage relative path_ to be more precise.
We recommend using the variable name `sp` for the _Storage (relative) Path_. The _storage path_ may not need to match the path on disk or whatever layout the storage driver implements. The `owncloud` storage driver may eg. inject a `files`, `files_trashbin` or `files_versions` segment before making os calls to actually read the data. The `ocis` storage driver deconstructs the folder structure and flattens everything into a `/nodes/<fileid>` hierarchy. These paths never leave the storage provider, so we recommend using `ip` which stands for _Internal Path_.

For logging we need to be able to distinguish an _internal path_ from an `ip` address. So we recommend a more verbose `spath` for the _storage (relative) path_ and `ipath` for _internal path_.

- [ ] The storage provider should not know where it is mounted, the gateway should add the prefix in the response.

# Path Wrapping functions

Translating between the _storage (relative) path_ the _internal path_ is done with a `wrap()` or `unwrap()` function. Because naming is hard. happy to find better names for these, eg. `asInternalPath()` or `convertToStoragePath()` ...

# TODO 
Sadly the path wrapping is where it gets confusing for people. Maybe the glossary and a common vocabulary helps.

**Comment by IljaN** [comment]
+1 for resolving wrap/unwrap confusion. Was also confusing for me. Also wrap/unwrap has received a new meaning in later golang versions. https://blog.golang.org/go1.13-errors

**Comment by madsi1m** [comment]
+1 for clear naming of things

**Comment by madsi1m** [comment]
maybe consistent reversible function names?

internalPathToStoragePath()
storagePathToInternalPath()

**Comment by butonic** [comment]
@madsi1m but that is soooooo long. also the signature should tell you in the param what is being converted:
```
toInternalPath(ctx context.Context, sp string) (ip string)
toStoragePath(ctx context.Context, ip string) (sp string)
```
where `ip` stands for _internal path_ and `sp` for _storage relative path_

**Comment by butonic** [comment]
outdated
